//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//     Versión del motor en tiempo de ejecución: 4.0.30319.17351
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion1
{


    public partial class BooleanFilter
    {

        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;
    }
}
